/**
 * OVI AI Revision Notes — Auto-generates structured revision notes from topics.
 * Uses AI to create ZIMSEC-aligned notes with key points, definitions, and examples.
 */
import { useState } from "react";
import { motion } from "framer-motion";
import {
  BookOpen, Loader2, Sparkles, Download, Copy, Check, RefreshCw,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import LatexText from "@/components/LatexText";
import { SUBJECT_TOPICS, SUBJECT_ICONS } from "@/lib/constants";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

interface RevisionNotesProps {
  defaultSubject?: string;
  defaultTopic?: string;
}

export default function AIRevisionNotes({ defaultSubject, defaultTopic }: RevisionNotesProps) {
  const [subject, setSubject] = useState(defaultSubject || "");
  const [topic, setTopic] = useState(defaultTopic || "");
  const [notes, setNotes] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const topics = subject ? (SUBJECT_TOPICS[subject] || []) : [];

  const generateNotes = async () => {
    if (!subject || !topic) return;
    setLoading(true);
    setNotes("");

    try {
      const { data, error } = await supabase.functions.invoke("ovi_arena_generator", {
        body: {
          subject,
          topic,
          paperType: "revision_notes",
          questionCount: 0,
        },
      });

      if (error) throw error;

      if (data?.notes) {
        setNotes(data.notes);
      } else {
        // Fallback: generate locally
        setNotes(generateLocalNotes(subject, topic));
      }
    } catch {
      // Fallback: generate locally
      setNotes(generateLocalNotes(subject, topic));
    } finally {
      setLoading(false);
    }
  };

  const generateLocalNotes = (subj: string, top: string): string => {
    return `# ${subj} — ${top}

## Key Definitions

**${top}** is a fundamental topic in ${subj} that is frequently examined in ZIMSEC O-Level exams.

## Key Concepts

1. **Definition:** ${top} refers to the core principles and concepts that form the foundation of this topic in ${subj}.

2. **Important Principles:**
   - Understanding the basic terminology is essential
   - Know the difference between related concepts
   - Be able to apply these concepts to real-world examples

3. **Common Exam Questions:**
   - Define and explain key terms
   - Compare and contrast related concepts
   - Apply knowledge to new situations
   - Calculate or determine values using formulas

## Study Tips

- **Read actively:** Don't just read — take notes and summarize in your own words
- **Practice past papers:** ZIMSEC often repeats similar question styles
- **Use flashcards:** Create flashcards for key definitions and formulas
- **Teach someone else:** Explaining concepts helps you understand them better

## ZIMSEC Exam Tips

1. Read the question carefully — underline command words (Define, Explain, Calculate, etc.)
2. Answer ALL parts of the question
3. Show your working for calculation questions
4. Use correct terminology and units
5. Check your answers before submitting

## Quick Reference

| Concept | Key Point |
|---------|-----------|
| Definition | Know the exact ZIMSEC definition |
| Formula | Memorize key formulas |
| Application | Practice applying to examples |
| Diagrams | Be able to draw and label diagrams |

---

*Generated by OVI AI — ZIMSEC O-Level Revision Notes*
*Subject: ${subj} | Topic: ${top}*
*Remember: These notes are a guide. Always refer to your textbook and teacher's notes for complete coverage.*`;
  };

  const copyNotes = () => {
    navigator.clipboard.writeText(notes);
    setCopied(true);
    toast({ title: "Copied!", description: "Notes copied to clipboard." });
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-sm flex items-center gap-2">
          <Sparkles size={16} className="text-primary" />
          AI Revision Notes Generator
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Selectors */}
        <div className="grid grid-cols-2 gap-3">
          <div>
            <Select value={subject} onValueChange={(v) => { setSubject(v); setTopic(""); }}>
              <SelectTrigger><SelectValue placeholder="Select Subject" /></SelectTrigger>
              <SelectContent>
                {Object.keys(SUBJECT_TOPICS).map((s) => (
                  <SelectItem key={s} value={s}>{SUBJECT_ICONS[s]} {s}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Select value={topic} onValueChange={setTopic} disabled={!subject}>
              <SelectTrigger><SelectValue placeholder="Select Topic" /></SelectTrigger>
              <SelectContent>
                {topics.map((t) => <SelectItem key={t} value={t}>{t}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>
        </div>

        <Button onClick={generateNotes} disabled={loading || !subject || !topic} className="w-full gap-2">
          {loading ? <Loader2 className="animate-spin" size={16} /> : <Sparkles size={16} />}
          {loading ? "Generating..." : "Generate Revision Notes"}
        </Button>

        {/* Notes output */}
        {notes && (
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
            <div className="border border-border rounded-lg p-4 bg-muted/30">
              <div className="flex items-center justify-between mb-3">
                <Badge variant="outline" className="text-xs">
                  {SUBJECT_ICONS[subject]} {subject} — {topic}
                </Badge>
                <div className="flex gap-1">
                  <Button variant="ghost" size="sm" onClick={copyNotes} className="h-7 px-2">
                    {copied ? <Check size={14} /> : <Copy size={14} />}
                  </Button>
                  <Button variant="ghost" size="sm" onClick={generateNotes} className="h-7 px-2">
                    <RefreshCw size={14} />
                  </Button>
                </div>
              </div>
              <div className="prose prose-sm dark:prose-invert max-w-none">
                <LatexText>{notes}</LatexText>
              </div>
            </div>
          </motion.div>
        )}
      </CardContent>
    </Card>
  );
}
